## 大作业
本次练习使用 鸢尾属植物数据集.\iris.data，在这个数据集中，包括了三类不同的鸢尾属植物：Iris Setosa，Iris Versicolour，Iris Virginica。每类收集了50个样本，因此这个数据集一共包含了150个样本。

- sepallength：萼片长度
- sepalwidth：萼片宽度
- petallength：花瓣长度
- petalwidth：花瓣宽度

以上四个特征的单位都是厘米（cm）。

- sepallength  sepalwidth  petallength  petalwidth         species
- 0            5.1         3.5          1.4         0.2     Iris-setosa
- 1            4.9         3.0          1.4         0.2     Iris-setosa
- 2            4.7         3.2          1.3         0.2     Iris-setosa
- 3            4.6         3.1          1.5         0.2     Iris-setosa
- 4            5.0         3.6          1.4         0.2     Iris-setosa
- ..           ...         ...          ...         ...             ...
- 145          6.7         3.0          5.2         2.3  Iris-virginica
- 146          6.3         2.5          5.0         1.9  Iris-virginica
- 147          6.5         3.0          5.2         2.0  Iris-virginica
- 148          6.2         3.4          5.4         2.3  Iris-virginica
- 149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]
[参考来源~ https://blog.csdn.net/weixin_46097969/article/details/110261921

1. 导入鸢尾属植物数据集，保持文本不变。

【知识点：输入和输出】

如何导入存在数字和文本的数据集？

In [2]:
from sklearn.datasets import load_iris
data = load_iris()
print(dir(data)) # 查看data所具有的属性或方法
print(data.DESCR) # 查看数据集的简介

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76 

In [3]:
import pandas as pd
#直接读到pandas的数据框中
pd.DataFrame(data=data.data, columns=data.feature_names)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
5                  5.4               3.9                1.7               0.4
6                  4.6               3.4                1.4               0.3
7                  5.0               3.4                1.5               0.2
8                  4.4               2.9                1.4               0.2
9                  4.9               3.1                1.5               0.1
10                 5.4               3.7                1.5               0.2
11                 4.8               3.4                1.6               0.2
12                 4.8               3.0                1.4               0.1
13                 4.3               3.0                1.1               0.1
14                 5.8               4.0                1.2               0.2
15                 5.7               4.4                1.5               0.4
16                 5.4               3.9                1.3               0.4
17                 5.1               3.5                1.4               0.3
18                 5.7               3.8                1.7               0.3
19                 5.1               3.8                1.5               0.3
20                 5.4               3.4                1.7               0.2
21                 5.1               3.7                1.5               0.4
22                 4.6               3.6                1.0               0.2
23                 5.1               3.3                1.7               0.5
24                 4.8               3.4                1.9               0.2
25                 5.0               3.0                1.6               0.2
26                 5.0               3.4                1.6               0.4
27                 5.2               3.5                1.5               0.2
28                 5.2               3.4                1.4               0.2
29                 4.7               3.2                1.6               0.2
..                 ...               ...                ...               ...
120                6.9               3.2                5.7               2.3
121                5.6               2.8                4.9               2.0
122                7.7               2.8                6.7               2.0
123                6.3               2.7                4.9               1.8
124                6.7               3.3                5.7               2.1
125                7.2               3.2                6.0               1.8
126                6.2               2.8                4.8               1.8
127                6.1               3.0                4.9               1.8
128                6.4               2.8                5.6               2.1
129                7.2               3.0                5.8               1.6
130                7.4               2.8                6.1               1.9
131                7.9               3.8                6.4               2.0
132                6.4               2.8                5.6               2.2
133                6.3               2.8                5.1               1.5
134                6.1               2.6                5.6               1.4
135                7.7               3.0                6.1               2.3
136                6.3               3.4                5.6               2.4
137                6.4               3.1                5.5               1.8
138                6.0               3.0                4.8               1.8
139                6.9     

In [4]:
import numpy as np
from sklearn import datasets

#导入库中数据集
iris=datasets.load_iris()
#将鸢尾四种类别数据转换为数组
iris_data=np.array(iris.data)
#创建鸢尾品种数组
k=np.array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])
#构建种类数组p
p=np.array([])
#前50个数据属于setosa类，50-100属于versicolor类，后50属于virginica
for i in range(150):
    p=np.append(p,k[i//50])
#数据连接
p=np.array(p).reshape(150,1)
iris_data=np.append(iris_data,p,axis=1)

#保存为iris数据为文本文档
np.savetxt('iris.txt',iris_data,fmt = '%s',delimiter=',',newline='\n',
          header='sepallength,sepalwidth,petallength,petalwidth,species')

#输入输出
print('导入鸢尾属植物数据集')

outfile=r'iris.txt'
iris_data=np.loadtxt(outfile,dtype=object,delimiter=',',skiprows=1)
print(iris_data[0:10])

导入鸢尾属植物数据集
[['5.1' '3.5' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.0' '1.4' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.3' '0.2' 'Iris-setosa']
 ['4.6' '3.1' '1.5' '0.2' 'Iris-setosa']
 ['5.0' '3.6' '1.4' '0.2' 'Iris-setosa']
 ['5.4' '3.9' '1.7' '0.4' 'Iris-setosa']
 ['4.6' '3.4' '1.4' '0.3' 'Iris-setosa']
 ['5.0' '3.4' '1.5' '0.2' 'Iris-setosa']
 ['4.4' '2.9' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.1' '1.5' '0.1' 'Iris-setosa']]


2. 求出鸢尾属植物萼片长度的平均值、中位数和标准差（第1列，sepallength）

【知识点：统计相关】

如何计算numpy数组的均值，中位数，标准差？

In [5]:
#统计相关
print('求萼片长度平均值、中位数和标准差（第一列数据）')
sepalLength=np.loadtxt(outfile,dtype=float,delimiter=',',skiprows=1,usecols=[0])
print('前10个萼片长度数据：','\n',sepalLength[0:10])

print('萼片长度平均值：',np.mean(sepalLength),'\t',np.average(sepalLength))
print('萼片长度中位数：',np.median(sepalLength),'\t',np.percentile(sepalLength,50))
print('萼片长度标准差：',np.std(sepalLength))

求萼片长度平均值、中位数和标准差（第一列数据）
前10个萼片长度数据： 
 [5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9]
萼片长度平均值： 5.843333333333334 	 5.843333333333334
萼片长度中位数： 5.8 	 5.8
萼片长度标准差： 0.8253012917851409


3. 创建一种标准化形式的鸢尾属植物萼片长度，其值正好介于0和1之间，这样最小值为0，最大值为1（第1列，sepallength）。

【知识点：统计相关】

如何标准化数组？

In [6]:
#统计相关
print('创建标准化的鸢尾植物萼片长度，使得值位于0-1之间')
#方法一：
#先求最大最小边界值
aMax=np.amax(sepalLength)
aMin=np.amin(sepalLength)
x=(sepalLength-aMin)/(aMax-aMin)
print('方法一前10个标准化数据：',x[0:10])
#方法二
x=(sepalLength-aMin)/np.ptp(sepalLength)
print('方法二前10个标准化数据：',x[0:10])

创建标准化的鸢尾植物萼片长度，使得值位于0-1之间
方法一前10个标准化数据： [0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556
 0.08333333 0.19444444 0.02777778 0.16666667]
方法二前10个标准化数据： [0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556
 0.08333333 0.19444444 0.02777778 0.16666667]


4. 找到鸢尾属植物萼片长度的第5和第95百分位数（第1列，sepallength）。

【知识点：统计相关】

如何找到numpy数组的百分位数？

In [7]:
#统计相关
print('找到鸢尾属萼片长度的第5和第95百分位数')
x=np.percentile(sepalLength,[5,95])
print('鸢尾萼片长度第5和第95分位数据：',x)

找到鸢尾属萼片长度的第5和第95百分位数
鸢尾萼片长度第5和第95分位数据： [4.6   7.255]


5. 把iris_data数据集中的20个随机位置修改为np.nan值。

【知识点：随机抽样】

如何在数组中的随机位置修改值？

In [8]:
#统计相关
print('创建标准化的鸢尾植物萼片长度，使得值位于0-1之间')
#方法一：
#先求最大最小边界值
aMax=np.amax(sepalLength)
aMin=np.amin(sepalLength)
x=(sepalLength-aMin)/(aMax-aMin)
print('方法一前10个标准化数据：',x[0:10])
#方法二
x=(sepalLength-aMin)/np.ptp(sepalLength)
print('方法二前10个标准化数据：',x[0:10])

#统计相关
print('找到鸢尾属萼片长度的第5和第95百分位数')
x=np.percentile(sepalLength,[5,95])
print('鸢尾萼片长度第5和第95分位数据：',x)

#统计相关
print('把iris_data数据集中第20个随机位置修改为np.nan值')
#方法一
#获取鸢尾数据集大小
i,j=iris_data.shape
np.random.seed(202011)
iris_data[np.random.randint(i,size=20),np.random.randint(j,size=20)]=np.nan
print('方法一前10个修改后的数据:',iris_data[0:10])

#方法二
iris_data=np.loadtxt(outfile,dtype=object,delimiter=',',skiprows=1)
iris_data[np.random.choice(i,size=20),np.random.choice(j,size=20)]=np.nan
print('方法二前10个修改后的数据:',iris_data[0:10])

创建标准化的鸢尾植物萼片长度，使得值位于0-1之间
方法一前10个标准化数据： [0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556
 0.08333333 0.19444444 0.02777778 0.16666667]
方法二前10个标准化数据： [0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556
 0.08333333 0.19444444 0.02777778 0.16666667]
找到鸢尾属萼片长度的第5和第95百分位数
鸢尾萼片长度第5和第95分位数据： [4.6   7.255]
把iris_data数据集中第20个随机位置修改为np.nan值
方法一前10个修改后的数据: [['5.1' '3.5' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.0' '1.4' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.3' '0.2' 'Iris-setosa']
 ['4.6' '3.1' '1.5' '0.2' 'Iris-setosa']
 ['5.0' '3.6' '1.4' '0.2' 'Iris-setosa']
 ['5.4' '3.9' '1.7' '0.4' 'Iris-setosa']
 ['4.6' '3.4' '1.4' '0.3' 'Iris-setosa']
 ['5.0' '3.4' '1.5' '0.2' 'Iris-setosa']
 ['4.4' '2.9' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.1' '1.5' '0.1' 'Iris-setosa']]
方法二前10个修改后的数据: [['5.1' '3.5' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.0' '1.4' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.3' '0.2' 'Iris-setosa']
 ['4.6' '3.1' '1.5' '0.2' 'Iris-setosa']
 ['5.0' '3.6' '1.4' '0.2' 'Ir

6. 在iris_data的sepallength中查找缺失值的个数和位置（第1列）。

【知识点：逻辑函数、搜索】

如何在numpy数组中找到缺失值的位置？

In [9]:
#逻辑函数，搜索
print('在iris_data数据集找那个的sepallength查找缺失值个数以及位置')
sepalLength=iris_data[:,0].astype('float')
x=np.isnan(sepalLength)
print('总共缺失值个数：',sum(x))
print('缺失位置：',np.where(x),'\t',x)

在iris_data数据集找那个的sepallength查找缺失值个数以及位置
总共缺失值个数： 5
缺失位置： (array([  6,  18,  45, 117, 125], dtype=int64),) 	 [False False False False False False  True False False False False False
 False False False False False False  True False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False  True False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False  True False False
 False False False False False  True False False False False False False
 False False False False False False False False False False False False
 False False Fal

7. 筛选具有 sepallength（第1列）< 5.0 并且 petallength（第3列）> 1.5 的 iris_data行。

【知识点：搜索】

如何根据两个或多个条件筛选numpy数组？

In [10]:
#搜索
print('筛选合适的值')
#读取前四列数据，float类型
iris_data=np.loadtxt(outfile,dtype=float,delimiter=',',skiprows=1,usecols=[0,1,2,3])
#获取萼片长度数据以及花瓣长度数据
sepalLength=iris_data[:,0]
petallength=iris_data[:,2]
#进行筛选数据
index=np.where(np.logical_and(petallength>1.5,sepalLength<5.0))
print('符合筛选条件的值：',iris_data[index])

筛选合适的值
符合筛选条件的值： [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


8. 选择没有任何 nan 值的 iris_data行。

【知识点：逻辑函数、搜索】

如何从numpy数组中删除包含缺失值的行？

In [11]:
#逻辑函数，搜索
print('选择没有nan值得行')
#随机将20个数据置为nan
iris_data[np.random.randint(i,size=20),np.random.randint(j-1,size=20)]=np.nan
#筛选数据
x=iris_data[np.sum(np.isnan(iris_data),axis=1)==0]
print('没有缺失数据的前10行：',x[0:10])

选择没有nan值得行
没有缺失数据的前10行： [[4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]]


9. 计算 iris_data 中sepalLength（第1列）和petalLength（第3列）之间的相关系数。

【知识点：统计相关】

如何计算numpy数组两列之间的相关系数？

In [12]:
#统计相关
print('计算sepallength和petallength两列相关系数')
#读取前四列数据，float类型
iris_data=np.loadtxt(outfile,dtype=float,delimiter=',',skiprows=1,usecols=[0,1,2,3])
#获取萼片长度数据以及花瓣长度数据
sepalLength=iris_data[:,0]
petallength=iris_data[:,2]
#方法一
#计算两列数据均值
m1=np.mean(sepalLength)
m2=np.mean(petallength)
#计算协方差矩阵
cov=np.dot(sepalLength-m1,petallength-m2)
#计算两列数据标准差
std1=np.sqrt(np.dot(sepalLength-m1,sepalLength-m1))
std2=np.sqrt(np.dot(petallength-m2,petallength-m2))
print('相关系数为：','\n',cov/(std1*std2))

#方法二
x=np.mean((sepalLength-m1)*(petallength-m2))
y=np.std(sepalLength)*np.std(petallength)
print('相关系数为：',x/y)

#方法3
x=np.cov(sepalLength,petallength,ddof=False)
y=np.std(sepalLength)*np.std(petallength)
print('相关系数：',x[0,1]/y)

计算sepallength和petallength两列相关系数
相关系数为： 
 0.8717537758865833
相关系数为： 0.8717537758865831
相关系数： 0.8717537758865835


10. 找出iris_data是否有任何缺失值。

【知识点：逻辑函数】

如何查找给定数组是否具有空值？

In [13]:
#逻辑函数
print('找出数据集是否有任何缺失值')
x=np.isnan(iris_data)
print('是否有缺失值：',np.any(x))

找出数据集是否有任何缺失值
是否有缺失值： False


11. 在numpy数组中将所有出现的nan替换为0。

【知识点：逻辑函数】

如何在numpy数组中用0替换所有缺失值？

In [14]:
#逻辑函数
print('将数组中所有出现的nan替换为0')
#随机将20个数据置为nan
iris_data[np.random.randint(i,size=20),np.random.randint(j-1,size=20)]=np.nan
#寻找值为nan的数据位置并且置为0
iris_data[np.isnan(iris_data)]=0
print('修改后前10行数据：',iris_data[0:10])

将数组中所有出现的nan替换为0
修改后前10行数据： [[0.  3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 0.  0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


12. 找出鸢尾属植物物种中的唯一值和唯一值出现的数量。

【知识点：数组操作】

如何在numpy数组中查找唯一值的计数？

In [15]:
#数组操作
print('找出鸢尾数据集中每一个值和出现的数量')
iris_data=np.loadtxt(outfile,dtype=float,delimiter=',',skiprows=1,usecols=[0,1,2,3])
x,p=np.unique(iris_data,return_counts=True)
print('每一个值和相应数量：')
print(x,'\n',p)

找出鸢尾数据集中每一个值和出现的数量
每一个值和相应数量：
[0.1 0.2 0.3 0.4 0.5 0.6 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1
 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9
 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7
 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4 7.6
 7.7 7.9] 
 [ 5 29  7  7  1  1  8  4  7 20 21 25 11  6 12  7  7  6  6 12  6 11  5  9
 14 10 27 11 13  8 12  8  5  4  7  5  6  4  5  3  8  9  7  7  9 11 14 17
  6  3  8 10 12 11 10  5  8  9  4 10  8  5  3 10  3  5  1  1  3  1  1  1
  4  1]


13. 将 iris_data 的花瓣长度（第3列）以形成分类变量的形式显示。定义：Less than 3 --> ‘small’；3-5 --> ‘medium’；’>=5 --> ‘large’。

【知识点：统计相关】

如何将数字转换为分类（文本）数组？

In [16]:
#统计相关
print('将数字转换为文本数组')
iris_data=np.loadtxt(outfile,dtype=float,delimiter=',',skiprows=1,usecols=[0,1,2,3])
#将数据分段表示
petal_length_bin=np.digitize(iris_data[:,2],[0,3,5,10])
#映射字典
label_map={1:'small',2:'medium',3:'larger',4:np.nan}
petal_length_cat=[label_map[x] for x in petal_length_bin]
print('前10个转换数据：',petal_length_cat[0:10])

将数字转换为文本数组
前10个转换数据： ['small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small']


14. 在 iris_data 中创建一个新列，其中 volume 是 (pi x petallength x sepallength ^ 2）/ 3。

【知识点：数组操作】

如何从numpy数组的现有列创建新列？

In [17]:
#数组操作
print('创建新列，其中volume是（pi*petallength*sepallength^2)/3')
#读取数据集
iris_data=np.loadtxt(outfile,dtype=object,delimiter=',',skiprows=1)
#读取sepallength数据并转换为float类型
sepalLength=iris_data[:,0].astype(float)
#读取petallength数据并转换为float类型
petallength=iris_data[:,2].astype(float)
volume=(np.pi*petallength*sepalLength**2)/3
volume=volume[:,np.newaxis]
#连接数据
iris_data=np.concatenate([iris_data,volume],axis=1)
print('前10行数据：',iris_data[0:10])

创建新列，其中volume是（pi*petallength*sepallength^2)/3
前10行数据： [['5.1' '3.5' '1.4' '0.2' 'Iris-setosa' 38.13265162927291]
 ['4.9' '3.0' '1.4' '0.2' 'Iris-setosa' 35.200498485922445]
 ['4.7' '3.2' '1.3' '0.2' 'Iris-setosa' 30.0723720777127]
 ['4.6' '3.1' '1.5' '0.2' 'Iris-setosa' 33.238050274980004]
 ['5.0' '3.6' '1.4' '0.2' 'Iris-setosa' 36.65191429188092]
 ['5.4' '3.9' '1.7' '0.4' 'Iris-setosa' 51.911677007917746]
 ['4.6' '3.4' '1.4' '0.3' 'Iris-setosa' 31.022180256648003]
 ['5.0' '3.4' '1.5' '0.2' 'Iris-setosa' 39.269908169872416]
 ['4.4' '2.9' '1.4' '0.2' 'Iris-setosa' 28.38324242763259]
 ['4.9' '3.1' '1.5' '0.1' 'Iris-setosa' 37.714819806345474]]


15. 随机抽鸢尾属植物的种类，使得Iris-setosa的数量是Iris-versicolor和Iris-virginica数量的两倍。

【知识点：随机抽样】

如何在numpy中进行概率抽样？

In [ ]:
#随机抽样
print('随机抽样')
species=np.array(['Iris-setosa','Iris-versicolor','Iris-virginica'])
species_out=np.random.choice(species,10000,p=[0.5,0.25,0.25])
print('随机抽取情况：',np.unique(species_out,return_counts=True))

16. 根据 sepallength 列对数据集进行排序。

【知识点：排序】

如何按列对2D数组进行排序？

In [18]:
#排序
print('根据sepallength列排序')
#读取数据集
iris_data=np.loadtxt(outfile,dtype=object,delimiter=',',skiprows=1)
#读取sepallength数据并转换为float类型
sepalLength=iris_data[:,0].astype(float)
index=np.argsort(sepalLength)
print('排序后前10行数据：',iris_data[index][0:10])

根据sepallength列排序
排序后前10行数据： [['4.3' '3.0' '1.1' '0.1' 'Iris-setosa']
 ['4.4' '3.2' '1.3' '0.2' 'Iris-setosa']
 ['4.4' '3.0' '1.3' '0.2' 'Iris-setosa']
 ['4.4' '2.9' '1.4' '0.2' 'Iris-setosa']
 ['4.5' '2.3' '1.3' '0.3' 'Iris-setosa']
 ['4.6' '3.6' '1.0' '0.2' 'Iris-setosa']
 ['4.6' '3.1' '1.5' '0.2' 'Iris-setosa']
 ['4.6' '3.4' '1.4' '0.3' 'Iris-setosa']
 ['4.6' '3.2' '1.4' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.3' '0.2' 'Iris-setosa']]


17. 在鸢尾属植物数据集中找到最常见的花瓣长度值（第3列）。

【知识点：数组操作】

如何在numpy数组中找出出现次数最多的值？

In [19]:
#数组操作
print('在数据集中找到最常见花瓣长度值')
petallength=iris_data[:,2]
vals,counts=np.unique(petallength,return_counts=True)
print('最常见花瓣长度：',vals[np.argmax(counts)])
print('最常见花瓣的数量：',np.amax(counts))

在数据集中找到最常见花瓣长度值
最常见花瓣长度： 1.4
最常见花瓣的数量： 13


18. 在鸢尾花数据集的 petalwidth（第4列）中查找第一次出现的值大于1.0的位置。

【知识点：搜索】

如何找到第一次出现大于给定值的位置？

In [20]:
#搜索
print('在数据集中找出petallength中第一次出现值大于1.0位置')
#读取petalwidth数据
petalwidth=iris_data[:,3].astype('float')
#筛选数据
index=np.where(petalwidth>1.0)
print('出现大于1.0值得位置：',index)
print('第一次出现大于1.0的位置：',index[0][0])

在数据集中找出petallength中第一次出现值大于1.0位置
出现大于1.0值得位置： (array([ 50,  51,  52,  53,  54,  55,  56,  58,  59,  61,  63,  64,  65,
        66,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  80,
        82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  94,  95,
        96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
       109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121,
       122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134,
       135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147,
       148, 149], dtype=int64),)
第一次出现大于1.0的位置： 50
